---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Makes sure OS is up to date
      yum:  name=* state=latest
    - name: Docker dependencies and others
      yum: name={{ item }} state=latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - git
        - vim
        - java-1.8.0-openjdk-devel
    - name: Docker repo
      get_url: url=https://download.docker.com/linux/centos/docker-ce.repo dest=/etc/yum.repos.d/docker.repo force=yes
    - name: Makes sure Docker is at its latest RHEL compatible version
      command: yum install -y --setopt=obsoletes=0 docker-ce-17.03.1.ce-1.el7.centos.x86_64
      args:
        warn: no
    - name: Docker is started now and at boot.
      service: name=docker state=started enabled=yes
    - name: Removes docker repo
      file: path=/etc/yum.repos.d/docker.repo state=absent
    - name: Download Kompose
      get_url:
        url: https://github.com/kubernetes/kompose/releases/download/v1.13.0/kompose-linux-amd64
        dest: /usr/local/bin/kompose
        mode: 0755
    - name: Adds mvn folder
      file: path=/usr/lib/mvn/ state=directory
    - name: Gets Maven installed
      unarchive:
        src: http://www-us.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.tar.gz
        dest: /usr/lib/mvn/
        remote_src: yes
    - name: Make mvn executable
      file:
        src: /usr/lib/mvn/apache-maven-3.5.3/bin/mvn
        dest: /usr/bin/mvn
        state: link
    - name: Make sure correct Java version selected
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/java-1.8.0/bin/java
    - name: Git clone
      git:
        repo: https://github.com/capitalone/Hygieia.git
        dest: ~/Hygieia
        clone: yes
      become: no




#> db.createUser({user:"dashboarduser",pwd:"mongo", roles:[{role:"readWrite", db:"dashboard"}]})
