---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Update OS
      yum: name=* state=latest
    - name: Install Java 8
      yum: name=java-1.8.0-openjdk state=latest
    - name: Correct Java version selected
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-7.b10.37.amzn1.x86_64/jre/bin/java
    - name: Get Jenkins Repository added
      get_url: url=https://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo force=yes
    - rpm_key:
        state: present
        key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key
    - name: Install Jenkins
      yum: name=jenkins state=present
    - name: Disable repo for possible updates updates
      command: "yum-config-manager --disable jenkins"
    - name: Change Jenkins default port from 8080 to 8081
      lineinfile:
        dest: /etc/sysconfig/jenkins
        regexp: 'JENKINS_PORT="8080"'
        line: 'JENKINS_PORT="8081"'
        backrefs: yes
    - name: Make sure Jenkins is started now and at boot.
      service: name=jenkins state=started enabled=yes
    - name: Echo jenkins secret first passwd
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: secret_result
    - debug: msg={{ secret_result.stdout }}
