---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Update OS
      yum: name=* state=latest
    - name: Install Java 8
      yum: name=java-1.8.0-openjdk state=latest
    - name: Correct Java version selected
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-8.b10.el7_5.x86_64/jre/bin/java
    - name: Installing Docker dependencies
      yum: name={{ item }} state=latest
      with_items:
        - docker
