---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Making sure there aren't any possible Docker conflict packages
      yum: name={{ item }} state=absent
      with_items:
        - docker
        - docker-ce
        - docker-ce-selinux
        - docker-common
        - docker-selinux
        - docker-engine-selinux
    - name: Makes sure OS is up to date
      yum: name=* state=latest
    - name: Makes sure Java 8 is present
      yum: name=java-1.8.0-openjdk state=latest
    - name: Make sure correct Java version selected
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.171-8.b10.el7_5.x86_64/jre/bin/java
    - name: Makes sure Docker is at its latest RHEL compatible version
      command: yum install -y --setopt=obsoletes=0 docker-ce-17.03.1.ce-1.el7.centos.x86_64
      args:
        warn: no
    - name: Make sure Docker is started now and at boot.
      service: name=docker state=started enabled=yes
    - name: Pull Jenkins docker image
      command: docker pull dacesmo/jenkins
    - name: Make sure Jenkins home exists
      file: path=/var/jenkins_home state=directory
    - name: Make sure K8s repo folder exists
      file: path=/var/opt/k8s state=directory
    - name: Run Jenkins instance
      command: docker run -d -u root -p 8081:8080 -p 50000:50000 -v /var/jenkins_home:/var/jenkins_home dacesmo/jenkins
    - name: Makes sure K8s
      git:
        repo: https://github.com/kubernetes/kubernetes
        dest: /var/opt/k8s
    - name: Install K8s
      make:
        chdir: /home/ubuntu/cool-project
        target: quick-release
