---
- hosts: jenkins
  become: yes
  remote_user: ec2-user
  tasks:
    - name: Get Jenkins Repository added
      command: "wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo && rpm --import http://pkg.jenkins.io/redhat-stable/jenkins.io.key"
    - name: Get Jenkins Repository added
      yum: name=jenkins state=present
    - name: Disable repo for possible updates updates
      command: "yum-config-manager --disable jenkins"
    - name: Make sure Jenkins is started now and at boot.
      service: name=jenkins state=started enabled=yes
    - name: Get port 8080 status
      command: "netstat -tulpn | grep 8080"
